export const LOC_MORROWS_REACH = 'LOC_MORROWS_REACH';
export const LOC_NEW_KRUCBURY = 'LOC_NEW_KRUCBURY';
export const LOC_IRON_BAY = 'LOC_IRON_BAY';
export const LOC_TWINS = 'LOC_TWINS';
export const LOC_ISLE_OF_PENANCE = 'LOC_ISLE_OF_PENANCE';
export const LOC_DREAD_VINE = 'LOC_DREAD_VINE';
export const LOC_GRAN_ALCAZAR = 'LOC_GRAN_ALCAZAR';
export const LOC_ANGLERS_GRAVE = 'LOC_ANGLERS_GRAVE';
export const LOC_CALAMITY_REEF = 'LOC_CALAMITY_REEF';
export const LOC_MEMORY = 'LOC_MEMORY';

export const MIS_RED_MARLEY_RISING = 'MIS_RED_MARLEY_RISING';
export const MIS_A_SHIP_NEEDS_A_CREW = 'MIS_A_SHIP_NEEDS_A_CREW';
export const MIS_THE_CAPTAINS_TREASURE = 'MIS_THE_CAPTAINS_TREASURE';
export const MIS_GAELLES_LETTER_CH3 = 'MIS_GAELLES_LETTER_CH3';
export const MIS_FRAGMENTS = 'MIS_FRAGMENTS';
export const MIS_SNATCHED_FROM_THE_PIT = 'MIS_SNATCHED_FROM_THE_PIT';
export const MIS_PINKUS_DUTY_CH1 = 'MIS_PINKUS_DUTY_CH1';
export const MIS_ASH_AND_ORE = 'MIS_ASH_AND_ORE';
export const MIS_TERESAS_LAMENT_CH1 = 'MIS_TERESAS_LAMENT_CH1';
export const MIS_QUENTINS_HUNT_CH2 = 'MIS_QUENTINS_HUNT_CH2';
export const MIS_PREPARE_FOR_TROUBLE = 'MIS_PREPARE_FOR_TROUBLE';
export const MIS_JOHNS_REVENGE_CH1 = 'MIS_JOHNS_REVENGE_CH1';
export const MIS_BONE_AND_FINGERS = 'MIS_BONE_AND_FINGERS';
export const MIS_FRUITS_OF_HER_LABOR = 'MIS_FRUITS_OF_HER_LABOR';
export const MIS_BARK_AND_BRAMBLE = 'MIS_BARK_AND_BRAMBLE';
export const MIS_HAGGLING_WITH_A_PLANT = 'MIS_HAGGLING_WITH_A_PLANT';
export const MIS_SULEIDYS_CURE = 'MIS_SULEIDYS_CURE';
export const MIS_INTO_THE_LIONS_DEN = 'MIS_INTO_THE_LIONS_DEN';
export const MIS_IGNACIA_UNLEASHED = 'MIS_IGNACIA_UNLEASHED';
export const MIS_PINKUS_DUTY_CH2 = 'MIS_PINKUS_DUTY_CH2';
export const MIS_TERESAS_LAMENT_CH2 = 'MIS_TERESAS_LAMENT_CH2';
export const MIS_GRAVEYARD_HAUNT = 'MIS_GRAVEYARD_HAUNT';
export const MIS_THE_KUMQUAT_CONNECTION = 'MIS_THE_KUMQUAT_CONNECTION';
export const MIS_GAELLES_LETTER_CH2 = 'MIS_GAELLES_LETTER_CH2';
export const MIS_JOHNS_REVENGE_CH2 = 'MIS_JOHNS_REVENGE_CH2';
export const MIS_TOYAS_PERFECTION_CH1 = 'MIS_TOYAS_PERFECTION_CH1';
export const MIS_LIGHTHOUSE_LOCUTIONS = 'MIS_LIGHTHOUSE_LOCUTIONS';
export const MIS_SMALL_CREW_BIG_PLANS = 'MIS_SMALL_CREW_BIG_PLANS';
export const MIS_GAELLES_LETTER_CH1 = 'MIS_GAELLES_LETTER_CH1';
export const MIS_TOYAS_PERFECTION_CH2 = 'MIS_TOYAS_PERFECTION_CH2';
export const MIS_QUENTINS_HUNT = 'MIS_QUENTINS_HUNT';
export const MIS_MEASURE_IS_UNCEASING = 'MIS_MEASURE_IS_UNCEASING';

export const CREW_AFIA = 'CREW_AFIA';
export const CREW_SULEIDY = 'CREW_SULEIDY';
export const CREW_PINKUS = 'CREW_PINKUS';
export const CREW_TERESA = 'CREW_TERESA';
export const CREW_TOYA = 'CREW_TOYA';
export const CREW_QUENTIN = 'CREW_QUENTIN';
export const CREW_GAELLE = 'CREW_GAELLE';
export const CREW_JOHN = 'CREW_JOHN';

export const BADGES = [
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_starting_concurrent_kill_enemy_types',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_starting_cross_wooden_bridge',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_starting_throw_down_distance',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_starting_throw_into_water_pit',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_starting_use_hidden_shrine',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_RED_MARLEY_RISING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_RED_MARLEY_RISING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_01_intro1_no_enter_ship_by_chain',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_RED_MARLEY_RISING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_01_intro1_no_kill_freezer',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_RED_MARLEY_RISING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_01_intro1_no_kill_or_ko_on_marley',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_RED_MARLEY_RISING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_01_intro1_no_time_freeze_bomb',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_RED_MARLEY_RISING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_load',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_A_SHIP_NEEDS_A_CREW,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_02_intro2_catatonic_simultaneous',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_A_SHIP_NEEDS_A_CREW,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_A_SHIP_NEEDS_A_CREW,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_02_intro2_no_alarm_limited_kill_or_ko',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_A_SHIP_NEEDS_A_CREW,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_swim',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_A_SHIP_NEEDS_A_CREW,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_solo_bln',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_A_SHIP_NEEDS_A_CREW,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_04_a3finale_capture_ships',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_THE_CAPTAINS_TREASURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_THE_CAPTAINS_TREASURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_kill_all',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_THE_CAPTAINS_TREASURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_04_a3finale_kill_freezer_simultaneous',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_THE_CAPTAINS_TREASURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_THE_CAPTAINS_TREASURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_starting_04_a3finale_overtake_inquisitor',
        nid: '0000',
        loc: LOC_MORROWS_REACH,
        mis: MIS_THE_CAPTAINS_TREASURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_trading_capture_the_flag',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_trading_extinguish_lights',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_trading_kill_all_within_time',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_trading_kill_by_envkill_within_time',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_trading_kill_custodes_within_time',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_GAELLES_LETTER_CH3,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_guns',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_GAELLES_LETTER_CH3,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_trading_02_cnn_no_kill_or_ko',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_GAELLES_LETTER_CH3,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_trading_02_cnn_no_kill_or_ko_warden',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_GAELLES_LETTER_CH3,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_load',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_GAELLES_LETTER_CH3,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_trading_02_cnn_no_whistlestone',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_GAELLES_LETTER_CH3,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_trading_03_intro3_all_memories_collected',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_FRAGMENTS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_FRAGMENTS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_trading_03_intro3_kill_sharpshooter_no_water',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_FRAGMENTS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_FRAGMENTS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_carry',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_FRAGMENTS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_trading_03_intro3_no_ladders_on_beach',
        nid: '0000',
        loc: LOC_NEW_KRUCBURY,
        mis: MIS_FRAGMENTS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_missions',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_furnace_forced_meditation',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_kill_all',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_furnace_kill_by_envkill',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_furnace_kill_freezer_tower',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_furnace_throw_coin_into_well',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_furnace_throw_freezer_into_pit',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_furnace_throw_tied_up_into_prison',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_01_pearl_enter_pit_not_from_bridge',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_SNATCHED_FROM_THE_PIT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_SNATCHED_FROM_THE_PIT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_01_pearl_limited_charset',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_SNATCHED_FROM_THE_PIT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_SNATCHED_FROM_THE_PIT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_01_pearl_no_fire_crates',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_SNATCHED_FROM_THE_PIT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_01_pearl_no_pickup_keys',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_SNATCHED_FROM_THE_PIT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_PINKUS_DUTY_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_climb',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_PINKUS_DUTY_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_PINKUS_DUTY_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_02_compass_no_prison',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_PINKUS_DUTY_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_02_compass_solo_ovt',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_PINKUS_DUTY_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_02_compass_use_secret_cave',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_PINKUS_DUTY_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_ASH_AND_ORE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_ASH_AND_ORE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_guns',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_ASH_AND_ORE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_03_soulenergy_no_kill_or_ko_in_bookshelfs',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_ASH_AND_ORE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_03_soulenergy_solo_bridge',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_ASH_AND_ORE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_03_soulenergy_throw_guard_into_pit',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_ASH_AND_ORE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_TERESAS_LAMENT_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_04_snp_kill_all_in_zen_garden',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_TERESAS_LAMENT_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_04_snp_limited_charset',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_TERESAS_LAMENT_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_climb',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_TERESAS_LAMENT_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_04_snp_no_doors',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_TERESAS_LAMENT_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_guns',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_TERESAS_LAMENT_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_QUENTINS_HUNT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_05_fsh_kill_freezer_no_enter_prison',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_QUENTINS_HUNT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_QUENTINS_HUNT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_furnace_05_fsh_no_bridge',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_QUENTINS_HUNT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_QUENTINS_HUNT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_02_mission2_no_planning',
        nid: '0000',
        loc: LOC_IRON_BAY,
        mis: MIS_QUENTINS_HUNT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_pillars_kill_from_ground_to_top',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_pillars_no_kill',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_pillars_switcheroo',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_pillars_use_bottle',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_pillars_use_door',
        nid: '0000',
        loc: LOC_TWINS,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_PREPARE_FOR_TROUBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_pillars_01_mission1_hide_in_both_bushes',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_PREPARE_FOR_TROUBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_pillars_01_mission1_hide_in_bushes',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_PREPARE_FOR_TROUBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_PREPARE_FOR_TROUBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_pillars_01_mission1_no_cave',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_PREPARE_FOR_TROUBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_pillars_01_mission1_no_kill_monks',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_PREPARE_FOR_TROUBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_JOHNS_REVENGE_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_pillars_02_gcw_kill_all_with_lanterns',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_JOHNS_REVENGE_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_pillars_02_gcw_limited_dig_in',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_JOHNS_REVENGE_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_JOHNS_REVENGE_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_lights_extinguished',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_JOHNS_REVENGE_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_swim',
        nid: '0000',
        loc: LOC_TWINS,
        mis: MIS_JOHNS_REVENGE_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_sfort_chain_reaction',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_sfort_kill_all_within_time',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_sfort_kill_ship_guard',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_sfort_firecracker_storage',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_sfort_throw_into_body_hatch',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: MIS_BONE_AND_FINGERS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_climb',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: MIS_BONE_AND_FINGERS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_doors',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: MIS_BONE_AND_FINGERS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_sfort_01_mission1_no_enter_tower',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: MIS_BONE_AND_FINGERS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_sfort_01_mission1_no_kill_or_ko_monk',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: MIS_BONE_AND_FINGERS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_sfort_01_mission1_no_kill_or_ko_outside_fort',
        nid: '0000',
        loc: LOC_ISLE_OF_PENANCE,
        mis: MIS_BONE_AND_FINGERS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_missions',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_ritual_concurrent_visit_inquisition_towers',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_ritual_find_hidden_grotto',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_kill_all',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_ritual_kill_by_toxic_plants',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_ritual_kill_custodes',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_ritual_throw_feed_dreadvine',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_ritual_visit_highest_point',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_01_mission1_collect_all_echoes',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_FRUITS_OF_HER_LABOR,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_FRUITS_OF_HER_LABOR,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_01_mission1_kill_all_in_camp',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_FRUITS_OF_HER_LABOR,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_FRUITS_OF_HER_LABOR,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_lights_extinguished',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_FRUITS_OF_HER_LABOR,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_01_mission1_steal_key_without_kill_or_ko',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_FRUITS_OF_HER_LABOR,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_BARK_AND_BRAMBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_02_mission2_limited_charset',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_BARK_AND_BRAMBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_02_mission2_no_kill_or_ko_on_beach',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_BARK_AND_BRAMBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_02_mission2_no_multiple_chars_on_beach',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_BARK_AND_BRAMBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_swim',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_BARK_AND_BRAMBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_02_mission2_search_creates_simultaneous',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_BARK_AND_BRAMBLE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_HAGGLING_WITH_A_PLANT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_HAGGLING_WITH_A_PLANT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_03_mission3_no_bridges',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_HAGGLING_WITH_A_PLANT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_HAGGLING_WITH_A_PLANT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_03_mission3_no_multiple_chars_on_island',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_HAGGLING_WITH_A_PLANT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_03_mission3_solo_kill_targets_no_alarm',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_HAGGLING_WITH_A_PLANT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_04_bsp_feed_dread_vine',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_SULEIDYS_CURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_SULEIDYS_CURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_04_bsp_kill_freezer_bsp',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_SULEIDYS_CURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_04_bsp_kill_monks_bsp',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_SULEIDYS_CURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_ritual_04_bsp_no_kill_before_examination',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_SULEIDYS_CURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_load',
        nid: '0000',
        loc: LOC_DREAD_VINE,
        mis: MIS_SULEIDYS_CURE,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_missions',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_fortress_conquer_island',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_fortress_hopeless_blacksmith',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_kill_all',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_fortress_kill_all_and_only_bell_guards',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_fortress_kill_lonely_sharpshooter',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_fortress_kill_sharpshooter_within_time',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_fortress_zen_garden',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_INTO_THE_LIONS_DEN,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_01_mission1_kill_custodes_three_times',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_INTO_THE_LIONS_DEN,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_01_mission1_kill_or_ko_only_melee',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_INTO_THE_LIONS_DEN,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_01_mission1_kill_sharpshooter_within_time',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_INTO_THE_LIONS_DEN,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_INTO_THE_LIONS_DEN,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_lights_extinguished',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_INTO_THE_LIONS_DEN,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_02_mission2_avoid_forced_unleash',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_IGNACIA_UNLEASHED,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_IGNACIA_UNLEASHED,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_IGNACIA_UNLEASHED,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_02_mission2_no_barracks_or_scriptorium',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_IGNACIA_UNLEASHED,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_IGNACIA_UNLEASHED,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_02_mission2_no_planning',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_IGNACIA_UNLEASHED,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_PINKUS_DUTY_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_03_ovt_kill_monks_scriptorium',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_PINKUS_DUTY_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_03_ovt_no_overtake_until_ceremony',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_PINKUS_DUTY_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_03_ovt_priest_first',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_PINKUS_DUTY_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_solo_ovt',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_PINKUS_DUTY_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_03_ovt_start_burial_as_priest',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_PINKUS_DUTY_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_TERESAS_LAMENT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_04_snp_judgement_before_confessor',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_TERESAS_LAMENT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_04_snp_kill_snipe',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_TERESAS_LAMENT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_04_snp_limited_charset',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_TERESAS_LAMENT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_TERESAS_LAMENT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_fortress_04_snp_no_climb_snp',
        nid: '0000',
        loc: LOC_GRAN_ALCAZAR,
        mis: MIS_TERESAS_LAMENT_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_missions',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_different_exits',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_head_to_tail',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_kill_all_in_fortress',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_kill_knocking_enemy',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_throw_freezer_into_water',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_use_all_graves',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_shanty_visit_crows_nest',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GRAVEYARD_HAUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_03_mission3_limited_charset',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GRAVEYARD_HAUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GRAVEYARD_HAUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_03_mission3_no_graveyard',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GRAVEYARD_HAUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_load',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GRAVEYARD_HAUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_03_mission3_solo_graveyard',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GRAVEYARD_HAUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_THE_KUMQUAT_CONNECTION,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_04_mission4_no_climb_agile',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_THE_KUMQUAT_CONNECTION,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_THE_KUMQUAT_CONNECTION,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_04_mission4_no_kill_or_ko_sharpshooter',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_THE_KUMQUAT_CONNECTION,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_04_mission4_no_outer_fort_ring',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_THE_KUMQUAT_CONNECTION,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_04_mission4_shoot_beschwerdetisch',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_THE_KUMQUAT_CONNECTION,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_05_cnn_arimtrice_garden',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GAELLES_LETTER_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GAELLES_LETTER_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_climb',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GAELLES_LETTER_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_05_cnn_no_drop_arimtrice',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GAELLES_LETTER_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_05_cnn_no_whistlestone',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GAELLES_LETTER_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_solo_cnn',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_GAELLES_LETTER_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_JOHNS_REVENGE_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_06_gcw_kill_all_at_pub',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_JOHNS_REVENGE_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_06_gcw_ledger',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_JOHNS_REVENGE_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_load',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_JOHNS_REVENGE_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_three_chars',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_JOHNS_REVENGE_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_06_gcw_yolanda',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_JOHNS_REVENGE_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_TOYAS_PERFECTION_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_07_tpb_merchant_a',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_TOYAS_PERFECTION_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_07_tpb_merchant_b',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_TOYAS_PERFECTION_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_shanty_07_tpb_no_climb_tpb',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_TOYAS_PERFECTION_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_kill_or_ko',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_TOYAS_PERFECTION_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_solo_tpb',
        nid: '0000',
        loc: LOC_ANGLERS_GRAVE,
        mis: MIS_TOYAS_PERFECTION_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_exits',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_missions',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_all_spawns',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_bfield_go_fishing',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_generic_kill_all',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_bfield_kill_by_envkills_within_time',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_bfield_lure_by_footprints_into_envkill',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_bfield_no_water',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_bfield_throw_monks_into_fire',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_loc_bfield_visit_lighthouse_top',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_LIGHTHOUSE_LOCUTIONS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_01_pearl_kill_freezer_before_lighthouse',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_LIGHTHOUSE_LOCUTIONS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_01_pearl_kill_on_lighthouse',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_LIGHTHOUSE_LOCUTIONS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_01_pearl_no_bridges',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_LIGHTHOUSE_LOCUTIONS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_bushes',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_LIGHTHOUSE_LOCUTIONS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_climb',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_LIGHTHOUSE_LOCUTIONS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_SMALL_CREW_BIG_PLANS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_kill_or_ko',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_SMALL_CREW_BIG_PLANS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_02_soulenergy_no_kill_or_ko_sharpshooter',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_SMALL_CREW_BIG_PLANS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_three_chars',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_SMALL_CREW_BIG_PLANS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_02_soulenergy_soul_trace_b',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_SMALL_CREW_BIG_PLANS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_02_soulenergy_soul_trace_a',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_SMALL_CREW_BIG_PLANS,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_03_cnn_cannon_multikill',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_GAELLES_LETTER_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_GAELLES_LETTER_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_GAELLES_LETTER_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_distractions',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_GAELLES_LETTER_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_03_cnn_no_kill_or_ko_monks_on_ship',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_GAELLES_LETTER_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_03_cnn_solo_ship',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_GAELLES_LETTER_CH1,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_TOYAS_PERFECTION_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_04_tpb_kill_sam_always_gun',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_TOYAS_PERFECTION_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_04_tpb_no_kill',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_TOYAS_PERFECTION_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_04_tpb_no_kill_or_ko_monks',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_TOYAS_PERFECTION_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_water',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_TOYAS_PERFECTION_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_solo_tpb',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_TOYAS_PERFECTION_CH2,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_QUENTINS_HUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_05_fsh_no_fsh_skills_beside_fishing',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_QUENTINS_HUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_kill_or_ko',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_QUENTINS_HUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_lights_extinguished',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_QUENTINS_HUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_load',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_QUENTINS_HUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_bfield_05_fsh_no_second_floor',
        nid: '0000',
        loc: LOC_CALAMITY_REEF,
        mis: MIS_QUENTINS_HUNT,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_finish_mission',
        nid: '0000',
        loc: LOC_MEMORY,
        mis: MIS_MEASURE_IS_UNCEASING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_granddes_01_mission1_military_first',
        nid: '0000',
        loc: LOC_MEMORY,
        mis: MIS_MEASURE_IS_UNCEASING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_alarm',
        nid: '0000',
        loc: LOC_MEMORY,
        mis: MIS_MEASURE_IS_UNCEASING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_generic_no_planning',
        nid: '0000',
        loc: LOC_MEMORY,
        mis: MIS_MEASURE_IS_UNCEASING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_granddes_01_mission1_science_first',
        nid: '0000',
        loc: LOC_MEMORY,
        mis: MIS_MEASURE_IS_UNCEASING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_mis_granddes_01_mission1_solo_multiple_freezer',
        nid: '0000',
        loc: LOC_MEMORY,
        mis: MIS_MEASURE_IS_UNCEASING,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 3,
    },
    {
        name: 'badge_cha_bln_frozen_in_distance',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_bln_kill_during_timefreeze',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 3,
    },
    {
        name: 'badge_cha_bln_kill_within_time',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_bln_solo_ritual',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_bln_timefreeze_in_conversation',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_bln_travel_blinking',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 3,
    },
    {
        name: 'badge_cha_bln_travel_blinking_upwards',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_AFIA,
        steps: 0,
    },
    {
        name: 'badge_cha_bsp_break_up_conversation',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 3,
    },
    {
        name: 'badge_cha_bsp_hide_corpses',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 3,
    },
    {
        name: 'badge_cha_bsp_hide_corpses_simultaneously',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 0,
    },
    {
        name: 'badge_cha_bsp_hide_player_simultaneously',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 3,
    },
    {
        name: 'badge_cha_bsp_solo_pillars',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 0,
    },
    {
        name: 'badge_cha_bsp_walk_away_distance',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 3,
    },
    {
        name: 'badge_cha_bsp_walk_away_into_envkill',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_SULEIDY,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 3,
    },
    {
        name: 'badge_cha_ovt_freezer_freeze_freezer',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 3,
    },
    {
        name: 'badge_cha_ovt_overtake_dev',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_ovt_overtaken_env_kill',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_ovt_ring_alarm_bell',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_ovt_solo_sfort',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_ovt_take_me_home',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_ovt_travel_overtaken',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 3,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_PINKUS,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 3,
    },
    {
        name: 'badge_cha_snp_kill_detecting_sharpshooter',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 3,
    },
    {
        name: 'badge_cha_snp_kill_or_ko_sharpshooters',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 3,
    },
    {
        name: 'badge_cha_snp_kill_or_ko_without_moving',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_snp_kills_over_distance',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_snp_kills_within_time',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_snp_solo_fortress',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_snp_visit_highest_points',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TERESA,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 3,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 3,
    },
    {
        name: 'badge_cha_tpb_kill_monks_without_alarm',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_tpb_solo_furnace',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_tpb_teleport_kill_detecting_sharpshooter',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_tpb_teleport_kill_ko_from_water',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_tpb_teleport_kill_multi_successive',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_tpb_teleport_travel',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_tpb_whistle_multi_acolytes_monks',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_TOYA,
        steps: 0,
    },
    {
        name: 'badge_cha_fsh_baited',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_fsh_concurrent_tanuki_watchers',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 3,
    },
    {
        name: 'badge_cha_fsh_fish_distance',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_fsh_fish_hide_bodies',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 3,
    },
    {
        name: 'badge_cha_fsh_forbidden_combo',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 3,
    },
    {
        name: 'badge_cha_fsh_lure_into_envkill',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_fsh_solo_trading',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_QUENTIN,
        steps: 0,
    },
    {
        name: 'badge_cha_cnn_carry_players_around',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 3,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 3,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 3,
    },
    {
        name: 'badge_cha_cnn_ko_freezer_with_freezer',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_cnn_long_range_character_pull',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_cnn_shoot_char_far_down_into_water',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_cnn_shoot_through_burning_ring',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_cnn_solo_shanty',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_cnn_take_dev_guard_home',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_GAELLE,
        steps: 0,
    },
    {
        name: 'badge_cha_gcw_dig_hide_bodies',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 3,
    },
    {
        name: 'badge_cha_gcw_dig_hide_from_alarm',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_cha_gcw_dig_kill_freezer',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_cha_gcw_dig_kills_in_single_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_cha_gcw_dig_multi_kill',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 3,
    },
    {
        name: 'badge_cha_gcw_fish_multi_distract',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_kill_ko',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 3,
    },
    {
        name: 'badge_cha_gcw_solo_bfield',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_cha_generic_visit_islands',
        nid: '0000',
        loc: null,
        mis: null,
        crew: CREW_JOHN,
        steps: 0,
    },
    {
        name: 'badge_gen_all_badges',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_all_badges_character',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_all_badges_location',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_all_badges_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_all_char_finish_mission',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_all_char_quests',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_all_chars_plan_execute_at_once',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_cannon_multi_kill',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_consecutive_alarm_duration',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_enter_marley',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_finish_mission_no_distractions',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_finish_mission_speedrun_any',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_finish_missions_hard_or_hardcore',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_finish_missions_no_alarms',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_finish_missions_no_kills',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hide_bodies',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_hub_all_char_upgrades_unlocked',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_all_chars_in_water',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_all_chars_unlocked',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_all_lights_extinguished_simultaneous',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_all_questlines_finished',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_kill_all_skeletons_before_revive',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_run_on_ship_from_end_to_end',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_shoot_skeleton_in_water',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_hub_unlock_trk',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_kill_devs',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_kill_enemies_environment',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_kill_inquisitor',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_kill_or_ko_enemies',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_kill_or_ko_enemies_within_time',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 0,
    },
    {
        name: 'badge_gen_kill_or_ko_freezers',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_kill_or_ko_monks',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
    {
        name: 'badge_gen_kill_or_ko_sharpshooters',
        nid: '0000',
        loc: null,
        mis: null,
        crew: null,
        steps: 3,
    },
];
